{{- if eq (toString .Values.license.enabled) "true" -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kong-license
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "dsb-kong.labels" . | nindent 4 }}
  annotations:
    {{ include "dsb-kong.annotations" . | nindent 4 }}
spec:
  provider: {{ .Values.license.secretProvider.provider | quote }}
  parameters: 
    {{- if eq (toString .Values.license.enabled) "true" -}}
    usePodIdentity: "false"
    clientID: {{ .Values.license.secretProvider.clientId | quote }}
    {{- else -}}
    usePodIdentity: "true"
    {{- end -}}
    keyvaultName: {{ .Values.license.secretProvider.name | quote }}
    cloudName: ""                         
    objects:  |
      array:
        - |
          objectName: kong-license
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: {{ .Values.license.secretProvider.tenantId | quote }}
  secretObjects:
  - data:
    - key: license
      objectName: kong-license
    secretName: kong-enterprise-license
    type: Opaque
{{- end -}}