# -----------------------------------------------------------------------------
# Example values file to use when installing a Kong data plane. Anything with the # CHANGEME comment should be overridden
# 
# Reach out to the Integration COE for help filling this out.
# -----------------------------------------------------------------------------

license:
  enabled: true
  keyvault:
    name: CHANGEME # The name of the key vault
    tenantId: CHANGEME # The guid for the tenant
    
kong:

  env:
    trusted_ips: CHANGE_ME # CHANGEME
    vitals_statsd_address: CHANGEME:9125 # The path to the statsd statsd-exporter service Ex. kong-prometheus-statsd-exporter.kong:9125
    vitals_tsdb_address: CHANGEME:80 # The path to prometheus Ex. prometheus-server.monitoring:80
    role: control_plane
    cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt # CHANGEME
    cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key # CHANGEME

  admin:
    enabled: true
    http:
      enabled: false
    tls:
      enabled: true
    ingress:
      enabled: true
      # TLS secret name.
      tls: CHANGEME-cert # Set the default certificate for the admin api
      # Ingress hostname
      hostname: CHANGEME.azure.dsb.dk # Set the hostname for the admin api
  
  cluster:
    enabled: true
    tls:
      enabled: true

  clustertelemetry:
    enabled: true
    tls:
      containerPort: 8006
      enabled: true
      servicePort: 8006
      type: ClusterIP

  proxy:
    enabled: false

  secretVolumes:
  - kong-cluster-cert

  ingressController:
    enabled: false

  enterprise:
    vitals:
        enabled: false
    portal:
      enabled: true
  manager:
    enabled: true
  portal:
    enabled: true
  portalapi:
    enabled: true

  podLabels:
      # Add the pod identity that Kong should use to access the key vault(s)
      aadpodidbinding: CHANGEME # CHANGEME


prometheus-statsd-exporter:
  enabled: false
  ingress:
    enabled: false