# -----------------------------------------------------------------------------
# Example values file to use when installing a Kong data plane. Anything with the # CHANGEME comment should be overridden
# 
# Reach out to the Integration COE for help filling this out.
# -----------------------------------------------------------------------------

license:
  enabled: true
  keyvault:
    name: CHANGEME # The name of the key vault
    tenantId: CHANGEME # The guid for the tenant

kong:

  env:
    trusted_ips: CHANGE_ME # CHANGEME
    vitals_statsd_address: CHANGEME:9125 # The path to the statsd statsd-exporter service Ex. kong-prometheus-statsd-exporter.kong:9125
    vitals_tsdb_address: CHANGEME:80 # The path to prometheus Ex. prometheus-server.monitoring:80
    role: data_plane
    cluster_control_plane: CHANGEME-control-service.CHANGEME-namespace.svc.cluster.local:8005 # CHANGEME
    cluster_telemetry_endpoint: CHANGEME-cluster-telemetry-service.CHANGEME-namespace.svc.cluster.local:8006 # CHANGEME
    lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt # CHANGEME
    cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt # CHANGEME
    cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key # CHANGEME

  secretVolumes:
  - kong-cluster-cert

  admin:
    enabled: false
  
  proxy:
    enabled: true
    ingress: 
      enabled: true
      ingressClassName: kong
      tls: CHANGEME
      hostname: CHANGEME
      annotations: {}

  ingressController:
    enabled: true
  enterprise:
    enabled: true
    vitals:
      enabled: true
    portal:
      enabled: false
  manager:
    enabled: false
  portal:
    enabled: false
  portalapi:
    enabled: false

  podLabels:
    # Add the pod identity that Kong should use to access the key vault(s)
    aadpodidbinding: CHANGEME # CHANGEME


prometheus-statsd-exporter:
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: kong
      konghq.com/protocols: https
      konghq.com/https-redirect-status-code: "301"
      konghq.com/regex-priority: "5"
    hosts:
      # Add the host to expose statsd on
      - host: CHANGEME # CHANGEME