# -----------------------------------------------------------------------------
# Example values file to use when installing a Kong ingress. All these values should be overridden
# 
# Reach out to the Integration COE for help filling this out.
# -----------------------------------------------------------------------------

kong:
  # -----------------------------------------------------------------------------
  # Kong parameters
  # -----------------------------------------------------------------------------

  env:
    # Add the trusted IPs here to allow Kong to communicate with on-prem systems.
    trusted_ips: CHANGE_ME # Add the trusted IPs here.
    vitals_statsd_address: CHANGEME:9125 # The path to the statsd statsd-exporter service Ex. kong-prometheus-statsd-exporter.kong:9125
    vitals_tsdb_address: CHANGEME:80 # The path to prometheus Ex. prometheus-server.monitoring:80

  admin:
    enabled: true
    http:
      enabled: true
    tls:
      enabled: false
    ingress:
      enabled: true
      # TLS secret name.
      tls: CHANGEME-cert # Set the default certificate for the admin api
      # Ingress hostname
      hostname: CHANGEME.azure.dsb.dk # Set the hostname for the admin api

  proxy:
    enabled: false
  ingressController:
    enabled: true
  enterprise:
    enabled: true
    vitals:
      enabled: true
    portal:
      enabled: false
  manager:
    enabled: false
  portal:
    enabled: false
  portalapi:
    enabled: false

  podLabels:
    # Add the pod identity that Kong should use to access the key vault(s)
    aadpodidbinding: CHANGEME # CHANGEME

prometheus-statsd-exporter:
  ingress:
    enabled: true
    hosts:
      # Add the host to expose statsd on
      - host: CHANGEME # CHANGEME