apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dsb-kong-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dsb-kong-controller.controller.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "dsb-kong-controller.controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dsb-kong-controller.controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.controller.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dsb-kong-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "dsb-kong-controller.fullname" . }}
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          image: {{ .Values.controller.image.url }}
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          env: 
            - name: ingress-suffix
              value: {{ .Values.controller.ingressSuffix | quote }}
            - name: kong-token
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.controller.kongTokenSecret }}
                  key: token
                  optional: false
            - name: kong-update
              value: {{ .Values.controller.kongUpdate | quote }}
            - name: kong-admin-url
              value: {{ .Values.controller.kongAdminUrl | quote }}
            - name: monitor-namespaces
              value: {{ .Values.controller.monitorNamespaces | quote }}              

      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
