apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dsb-kong-controller.fullname" . }}
rules:
- apiGroups: ['dsb.dk']
  resources: ['*']
  verbs: ['*']
- apiGroups:
    - ''
  resources:
    - services
    - pods
  verbs:
    - get
    - list  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dsb-kong-controller.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dsb-kong-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dsb-kong-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
