{{- if .Values.portal.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dsb-kong-controller.portal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.portal.ingressAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.portal.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.portal.ingress }}
      secretName: {{ include "dsb-kong-controller.portal.fullname" . }}
  rules:
    - host: {{ .Values.portal.ingress }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "dsb-kong-controller.portal.fullname" . }}
                port:
                  number: 8090
{{- end }}
