{{- if .Values.portal.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dsb-kong-controller.portal.fullname" . }}
  labels:
    {{- include "dsb-kong-controller.portal.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: 8090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dsb-kong-controller.portal.selectorLabels" . | nindent 4 }}
{{- end }}